openapi: 3.1.0
info:
  version: 0.1.0
  title: OpenFeature Remote Evaluation Protocol (OFREP)
  description: OFREP define the protocol for remote flag evaluations
  contact:
    url: https://github.com/open-feature/protocol
  license:
    name: Apache 2.0
security:
  - ApiKeyAuth: []
  - BearerAuth: []
paths:
  /ofrep/v1/flags/{key}:
    post:
      description: Evaluate an individual flag
      tags:
        - evaluate
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/evaluationRequest'
      responses:
        '200':
          description: OFREP successful evaluation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
        '400':
          description: OFREP error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
        '401':
          description: Unauthorized - You need credentials to access the API
        '403':
          description: Forbidden - You are not authorized to access the API
        '404':
          description: Flag not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
        '429':
          description: Rate limit reached on the Flag Management System
          headers:
            Retry-Later:
              description: Indicates when to retry the request
              schema:
                type: string
                format: date-time
                example: '2024-02-07T12:00:00Z'
        '500':
          description: Internal server error
  /ofrep/v1/flags:
    post:
      description: Bulk evaluate multiple flags
      tags:
        - evaluate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bulkEvaluationRequest'
      responses:
        '200':
          description: OFREP successful evaluation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bulkEvaluationSuccess'
        '400':
          description: OFREP error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bulkEvaluationFailure'
        '401':
          description: Unauthorized - You need credentials to access the API
        '403':
          description: Forbidden - You are not authorized to access the API
        '429':
          description: Rate limit reached on the Flag Management System
          headers:
            Retry-Later:
              description: Indicates when to retry the request
              schema:
                type: string
                format: date-time
                example: '2024-02-07T12:00:00Z'
        '500':
          description: Internal server error
components:
  securitySchemes:
    BearerAuth:
      description: (optional) Bearer Authorization to your flag management system
      type: http
      scheme: bearer
    ApiKeyAuth:
      description: (optional) API Key to your flag management system
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    bulkEvaluationRequest:
      description: Bulk evaluate multiple flags
      properties:
        context:
          $ref: '#/components/schemas/context'
    bulkEvaluationSuccess:
      description: Response of the bulk evaluation
      properties:
        flags:
          type: array
          items:
            properties:
              key:
                $ref: '#/components/schemas/key'
              value:
                type: object
                description: Flag evaluation result
              reason:
                type: string
                description: Reason matching OpenFeature reason
                externalDocs:
                  url: https://openfeature.dev/specification/types#resolution-details
              variant:
                type: string
                description: Variant of the evaluated flag value
              metadata:
                type: object
                description: Arbitrary metadata supporting flag evaluation
              errorCode:
                type: string
                description: OpenFeature compatible error code.
                externalDocs:
                  url: https://openfeature.dev/specification/types#error-code
              errorDetails:
                type: string
                description: Optional error details description for logging or other needs
            required:
              - key
    bulkEvaluationFailure:
      description: Bulk evaluation failure response.
      properties:
        errorCode:
          type: string
          description: Error code specific to the bulk evaluation.
        errorDetails:
          type: string
          description: Optional error details description for logging or other needs
      required:
        - errorCode
    evaluationRequest:
      description: Flag evaluation request
      properties:
        context:
          $ref: '#/components/schemas/context'
    success:
      description: Flag evaluation success response.
      properties:
        key:
          $ref: '#/components/schemas/key'
        value:
          type: object
          description: Flag evaluation result
        reason:
          type: string
          description: Reason matching OpenFeature reason
        variant:
          type: string
          description: Variant of the evaluated flag value
        metadata:
          type: object
          description: Arbitrary metadata supporting flag evaluation
      required:
        - key
        - value
    failure:
      description: Flag evaluation failure response
      properties:
        key:
          $ref: '#/components/schemas/key'
        errorCode:
          type: string
          enum:
           - FLAG_NOT_FOUND
           - PARSE_ERROR
           - TYPE_MISMATCH
           - TARGETING_KEY_MISSING
           - INVALID_CONTEXT
           - GENERAL
          description: OpenFeature compatible error code.
          externalDocs:
            url: https://openfeature.dev/specification/types#error-code
        errorDetails:
          type: string
          description: Optional error details description for logging or other needs
      required:
        - key
        - errorCode
    key:
      type: string
      description: Feature flag key
      example: my-flag
    context:
      type: object
      description: Context information for flag evaluation